name: Copilot Auto Merge

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'github-copilot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge --auto --merge ${{ github.event.pull_request.html_url }}
